
# 
# Name:  Uptime kuma
# Description:  A helpful and flexible uptime and status page
# 

services:
  status:
    container_name: uptime-kuma 
    image: louislam/uptime-kuma:1
    restart: always 
    # ports: 
      # - 127.0.0.1:3001:3001 
    volumes: 
    - ./data__uptime-kuma:/app/data
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    labels:
      - portainer.hidden=true
      - traefik.enable=true
      - traefik.http.routers.statusPage.tls.certresolver=cf
      - traefik.http.routers.statusPage.rule=Host(`status.YOURDOMAIN.COM`)
      # - traefik.http.routers.statusPage.middlewares=authentik@docker
      - traefik.http.routers.statusPage.entrypoints=websecure
      - traefik.http.services.statusPage.loadbalancer.server.port=3001


networks:
  frontend:
    external: true