
# 
# Name:  Crossplatform Minecraft Server
# Description:  Paper Minecraft server with Plugins to enable crossplatform play with bedrock players
# 

# Minecraft Java Paper Server + Geyser + Floodgate Docker Container - Docker Compose
# Author: James A. Chambers - https://jamesachambers.com/minecraft-java-bedrock-server-together-geyser-floodgate/
# GitHub Repository: https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate

# To run multiple servers change the volume name under both "volumes" sections and select different ports
# version: "3.5"
services:
  cp-minecraft:
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    container_name: cp-minecraft
    restart: "unless-stopped"
    networks:
      - frontend
    ports:
      - 25565:25565
      - 19132:19132
      - 19132:19132/udp
    volumes:
      - ./data__cp-minecraft.minecraft:/minecraft
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [ "/bin/bash", "/scripts/start.sh" ]
    # Environment variables
    environment:
      Port: "25565"
      BedrockPort: "19132"
      TZ: "Europe/London" # Timezone
      BackupCount: 5 # Number of rolling backups to keep
      MaxMemory: 2048 # Maximum memory usage for Java
      # Version: 1.19.3 # Use custom version
      NoBackup: "plugins" # Optional folder to skip during backups
      QuietCurl: "Y" # Optional flag to reduce curl log output by suppressing progress meter
      # NoPermCheck: "Y" # Optional flag to skip permissions check
      # NoViaVersion: "Y" # Optional flag to disable ViaVersion plugin

networks:
  frontend:
    external: true